default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5433
  user: postgres
  schema_search_path: public

development:
  <<: *default
  database: cirruslabs_task_development

test:
  <<: *default
  database: cirruslabs_task_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
